version: "3.3"
services:
        pia-openvpn:
                container_name: "PIA"
                restart: always
                dns:
                        - 209.222.18.222
                        - 209.222.18.218
                        - 209.222.18.220
                cap_add:
                        - NET_ADMIN
                environment:
                        - USERNAME=${PIA_USER}
                        - PASSWORD=${PIA_PASS}
                image: itsdaspecialk/pia-openvpn:centos7
                ports:
                        - 51413:51413
                        - 51413:51413/udp
                networks:
                        pia_network:
                                ipv4_address: 192.168.170.6
        portainer:
                image: portainer/portainer:latest
                container_name: "Portainer"
                restart: always
                volumes:
                        - /var/run/docker.sock:/var/run/docker.sock
                        - portainer_data:/data
                ports:
                        - "9000:9000"
        transmission:
                image: linuxserver/transmission:latest
                container_name: "Transmission"
                network_mode: "service:pia-openvpn"
                environment:
                        - VIRTUAL_HOST=transmission.local
                        - PUID=${PUID}
                        - PGID=${PGID}
                        - TZ=${TZ}
                volumes:
                        - ${DOCK_ROOT}/transmission/config:/config
                        - ${ROOT}/downloads:/downloads
                        - ${DOCK_ROOT}/transmission/watch:/watch
                restart: unless-stopped
        nzbget:
                image: linuxserver/nzbget:latest
                container_name: "Nzbget"
                #network_mode: "service:pia-openvpn"
                ports:
                        - "6789:6789"
                environment:
                        - VIRTUAL_HOST=nzbget.local
                        - PUID=${PUID}
                        - PGID=${PGID}
                        - TZ=${TZ}
                volumes:
                        - ${DOCK_ROOT}/nzbget/config:/config
                        - ${ROOT}/downloads:/downloads
                restart: unless-stopped
        proxy:
                container_name: "Vpn-Proxy"
                image: nginx:latest
                restart: always
                volumes:
                        - ${DOCK_ROOT}/proxy/config/nginx.conf:/etc/nginx/nginx.conf:ro
                ports:
                        - "9091:9091"
                        #- "6789:6789"
                environment:
                        - TZ=${TZ}
                        - PGID=${PGID}
                        - PUID=${PUID}
                networks:
                        pia_network:
                                ipv4_address: 192.168.170.5
        sonarr:
                container_name: Sonarr
                #image: linuxserver/sonarr:133
                image: linuxserver/sonarr:latest
                restart: unless-stopped
                volumes:
                        - ${DOCK_ROOT}/sonarr/config:/config
                        - ${ROOT}/tv:/complete
                        - ${ROOT}/downloads:/downloads
                        - /etc/localtime:/etc/localtime:ro
                environment:
                        - TZ=${TZ}
                        - PGID=${PGID}
                        - PUID=${PUID}
                ports:
                        - "8989:8989"
                networks:
                        pia_network:
                                ipv4_address: 192.168.170.8

        radarr:
                container_name: Radarr
                #image: linuxserver/radarr:109
                image: linuxserver/radarr:latest
                restart: unless-stopped
                volumes:
                        - ${DOCK_ROOT}/radarr/config:/config
                        - ${ROOT}/movies:/complete
                        - ${ROOT}/downloads:/downloads
                        - /etc/localtime:/etc/localtime:ro
                environment:
                        - TZ=${TZ}
                        - PGID=${PGID}
                        - PUID=${PUID}
                ports:
                        - "7878:7878"
                networks:
                        pia_network:
                                ipv4_address: 192.168.170.10
        ombi:
                container_name: Ombi
                image: linuxserver/ombi:latest
                restart: always
                volumes:
                        - ${DOCK_ROOT}/ombi/config:/config
                environment:
                        - TZ=${TZ}
                        - PUID=${PUID}
                        - PGID=${PGID}
                ports:
                        - "3579:3579"


volumes:
        portainer_data:

networks:
        pia_network:
                driver: bridge
                ipam:
                        config:
                                - subnet: 192.168.170.0/24
